name: PR Validation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x
          include-prerelease: true

      - name: Restore
        run: dotnet restore LexiDiff.sln

      - name: Build
        run: dotnet build LexiDiff.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test LexiDiff.sln --configuration Release --no-build --logger "trx;LogFileName=tests.trx"
